version: "3.0"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: bakkkweb
      POSTGRES_PASSWORD: bakkkweb
      POSTGRES_DB: bakkkweb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
